language: dart
dist: xenial

install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter config --enable-web
script:
  - ./flutter/bin/flutter format --set-exit-if-changed lib test
  - ./flutter/bin/flutter analyze
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter build web

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/web